language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: H7QuZvlzkRJXoKq2lrlrl1GlH4Dg9Lr+kSzTEJz+sXyDbGnrWdN6i6m+3d4pC6qrvmue22SnpJSNScupELa4P5XK83Dod4JuS+yIPe/JZEfZXEdQs9VGBJntQYw+8Xx7+C9fAAf+rQHZ1G/rNbYtCFbG2hiqgWF/U4NAsYrIUUnjSrQK6YmVf9uMfuJSWF0nJSYiI1pp/dE1u3DbzfoR9AeShFRDCWAoFeK9gEEoo1jeQ60QhJg9bKOuy3kBvzQS1Ckv6O7ee2I2ACXKGkH2PCl1ILbYoQ1G0kncF+alLFjn/SflaXASMkTM3sLKF+nLTXv+0YZ5Fi/8RIffTYBJL78QsamL8SRkgijbuuiCvVuxsQZmpuAIYSm2Icqn/WVyxNbcqFXGQpQ+U6OzXnnpQERK9NT00d0vupVjFsZg9dBGTVoMxBlg6/vvL13IbyqXckxNum7YIzs4w5VXq/ZU+EMtdok7RJsynyOb32fMTLEuw/sizwcacO9Lwg0FjD77AUmLW5tkjEkYgOo4NXGMJSQz5v2M5dn4x1jvFZysUvTARMpQVFL6NTikQTX3q5o9C8I015p4Nu2Yxyz352TFiY30yvE5sJPlFmIS9TGdCwAp0ivJ8dwNEJquO2To6EJ158Agj29qVBeM6b486pfu953YhCE8Gc/5qYgH9YuPmuI=
  app: projet-lc
  run: rake db:migrate
before_script:
- psql -c 'create database db_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter format-coverage -t simplecov
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter upload-coverage; fi
env:
  global:
    secure: rxE5iiPX0+n/l12AqS80b2D+InqqmwLwbcAlfI+wb6uLkNWUAHn2gcpcMtsW+xhGerjBDa8U0bJhNyESay665/GSGV7Q4fpdrpvOuyFbUyAqIThem0hoyKyO7ZLefHuL11CAWzsrtWp8H0MesSnA13w7h/GVArFObh/IPgns6W/qDv9gqCXPEXC+CJroLekN0ymDtOvqFzqHxhh5wCYMsIMLszT4DYVJgbfqr+HWKZY5gtIQ0iLgh79QXlcE89hefPVxnYFoRthpfOjb/JRnTpAmND0pXTyMK/lrCgu4x/itJQer+x9yniQ+9oELXr4UY4EmvgUim+tg4fCLUKOSjWn766V2EYPcgYzz4Zc+lAYzvDqRTX1JeD++yYzZ4y84d4dJGHvrTOz4Us8ZG7ULGxWtJHdag6bijrAYcSZJVlFGseVa7Of6vnzIs97QW8gnrvNVcNMI5HnAbCTQUUVwxsdFXwZeL9C1A2JI4eOmKr8HShkjt0Yg/voP5qnt1FVl/5yByv+/+1fjrUXDVIhauj95HY5zB6WE1QfN+WSbCG1GzIVzsQIHiF9MejAA3ZvzWD8LCDIj3js5v79ANzZa4sLHZcxr7d+mr41h3lqWaH/uwJA7SBiakQr4WaFX3sbQ9FsU7uPPMnKgnr+HO5i96Z70hphlEnjFBV2b6Is8HF8=
