language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: Bo6E+sP/iZ23kWUS9CEB24dtpCeTIjavXE5sB0gbUZHF2lUojHLEqlIiWAknSyBj9U8KtpaDiIm6fgyCP9HYkj6ZhFVti7or7RaTpnp0Fod3PeiCswDgvXkkQ7q9jsz7NORBlzbmKHbH1tK2eNvCliZlYIUzCpFTM0SPOi4OBKNHu//gzO5LpKPQX9gpcamFQQzGcxxTQ8US04hyn3uEyzazt8BmdL9C96l1kspQ3/n3El9axTjbsrluvhwv14zIBu8/ldmTegDtCG8XqdRwiI8o/qK2VU14+9+xUuCz333ZcgSCHgRBUei9SMRbw0bpbwThjVESir6P50xaAYnYihMD4OP5iToAilepSO5+HrJdug7OPCsjO0jydc5T0im3/yf7u9UYEVjAAeKTw8IP8rwkZuvV9NU77dg/zqcp/ZaTL4ERkfgNVSWSZ211CO1P0lwYFKpSt7z5aNA/bv2KSd4O/3tXRyTdCN7ciPxUezSO97LX5bjJbd/UpinPGtYq/ucJuAyOt4+ZcDBscTXJNoks5WarIN1zAReKcIzX6oK7LwqJXco2UHoN7M+UShQgmttWp4+qFk4QEt98vXuaRngWl+0WVaYi+TTGRhI8dMJ7xk1WyS9wpxpnXFEetVaFVhw369uNxCs65Z6OuIp+OcQKiyJmob1oDEO5kbzQvcM=
  app: projet-lc