language: ruby
rvm:
- 2.3.5
deploy:
  provider: heroku
  api_key:
    secure: H7QuZvlzkRJXoKq2lrlrl1GlH4Dg9Lr+kSzTEJz+sXyDbGnrWdN6i6m+3d4pC6qrvmue22SnpJSNScupELa4P5XK83Dod4JuS+yIPe/JZEfZXEdQs9VGBJntQYw+8Xx7+C9fAAf+rQHZ1G/rNbYtCFbG2hiqgWF/U4NAsYrIUUnjSrQK6YmVf9uMfuJSWF0nJSYiI1pp/dE1u3DbzfoR9AeShFRDCWAoFeK9gEEoo1jeQ60QhJg9bKOuy3kBvzQS1Ckv6O7ee2I2ACXKGkH2PCl1ILbYoQ1G0kncF+alLFjn/SflaXASMkTM3sLKF+nLTXv+0YZ5Fi/8RIffTYBJL78QsamL8SRkgijbuuiCvVuxsQZmpuAIYSm2Icqn/WVyxNbcqFXGQpQ+U6OzXnnpQERK9NT00d0vupVjFsZg9dBGTVoMxBlg6/vvL13IbyqXckxNum7YIzs4w5VXq/ZU+EMtdok7RJsynyOb32fMTLEuw/sizwcacO9Lwg0FjD77AUmLW5tkjEkYgOo4NXGMJSQz5v2M5dn4x1jvFZysUvTARMpQVFL6NTikQTX3q5o9C8I015p4Nu2Yxyz352TFiY30yvE5sJPlFmIS9TGdCwAp0ivJ8dwNEJquO2To6EJ158Agj29qVBeM6b486pfu953YhCE8Gc/5qYgH9YuPmuI=
  app: projet-lc
  run: rake db:migrate
before_script:
- psql -c 'create database db_test;' -U postgres
